config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :cuisines
  root 'store#index', as: 'store_index'

  get 'store/index'

  resources :reviews
  resources :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cuisine.rb
# == Schema Information
#
# Table name: cuisines
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cuisine < ApplicationRecord
  validates :name , presence: true, allow_blank: false
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :set_cuisine, only: [:show, :edit, :update, :destroy]

  # GET /cuisines
  # GET /cuisines.json
  def index
    @cuisines = Cuisine.all
  end

  # GET /cuisines/1
  # GET /cuisines/1.json
  def show
  end

  # GET /cuisines/new
  def new
    @cuisine = Cuisine.new
  end

  # GET /cuisines/1/edit
  def edit
  end

  # POST /cuisines
  # POST /cuisines.json
  def create
    @cuisine = Cuisine.new(cuisine_params)

    respond_to do |format|
      if @cuisine.save
        format.html { redirect_to @cuisine, notice: 'Cuisine was successfully created.' }
        format.json { render :show, status: :created, location: @cuisine }
      else
        format.html { render :new }
        format.json { render json: @cuisine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cuisines/1
  # PATCH/PUT /cuisines/1.json
  def update
    respond_to do |format|
      if @cuisine.update(cuisine_params)
        format.html { redirect_to @cuisine, notice: 'Cuisine was successfully updated.' }
        format.json { render :show, status: :ok, location: @cuisine }
      else
        format.html { render :edit }
        format.json { render json: @cuisine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuisines/1
  # DELETE /cuisines/1.json
  def destroy
    @cuisine.destroy
    respond_to do |format|
      format.html { redirect_to cuisines_url, notice: 'Cuisine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cuisine
      @cuisine = Cuisine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cuisine_params
      params.require(:cuisine).permit(:name)
    end
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/views/cuisines/_form.html.erb
<%= form_with(model: cuisine, local: true) do |form| %>
  <% if cuisine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cuisine.errors.count, "error") %> prohibited this cuisine from being saved:</h2>

      <ul>
      <% cuisine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cuisine_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cuisines/edit.html.erb
<h1>Editing Cuisine</h1>

<%= render 'form', cuisine: @cuisine %>

<%= link_to 'Show', @cuisine %> |
<%= link_to 'Back', cuisines_path %>

app/views/cuisines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cuisines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cuisines.each do |cuisine| %>
      <tr>
        <td><%= cuisine.name %></td>
        <td><%= link_to 'Show', cuisine %></td>
        <td><%= link_to 'Edit', edit_cuisine_path(cuisine) %></td>
        <td><%= link_to 'Destroy', cuisine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cuisine', new_cuisine_path %>

app/views/cuisines/new.html.erb
<h1>New Cuisine</h1>

<%= render 'form', cuisine: @cuisine %>

<%= link_to 'Back', cuisines_path %>

app/views/cuisines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cuisine.name %>
</p>

<%= link_to 'Edit', edit_cuisine_path(@cuisine) %> |
<%= link_to 'Back', cuisines_path %>