config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :cuisines
  root 'store#index', as: 'store_index'

  get 'store/index'

  resources :reviews
  resources :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id                :integer          not null, primary key
#  name              :string
#  rating            :decimal(, )      default(0.0)
#  ten_bis           :boolean
#  address           :string
#  max_delivery_time :decimal(, )      default(0.0)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  cuisine_id        :integer
#  kosher            :boolean
#

class Restaurant < ApplicationRecord
  has_many :reviews , dependent: :destroy
  has_many :users , through: :reviews
  belongs_to :cuisine

  validates :name, presence: true, allow_nil: false, allow_blank: false
  validates :name, uniqueness: true

  def update_rating!
    update!(rating: calculate_rating)
  end

  def parse_csv(file_name)
    require 'csv'
    csv_text = File.read(Rails.root.join('lib', 'seeds', file_name))
    csv = CSV.parse(csv_text, headers: true, encoding: 'ISO-8859-1')

    csv.each do |row|
      t = Restaurant.new
      cur_cuisine = Cuisine.find_by name: row['Cuisine']
      t.cuisine_id = cur_cuisine.id
      # couldnt get data by row['Name']
      t.name = row[0]
      t.kosher = row['Kosher']
      t.ten_bis = row['10bis']
      t.address = row['Address']
      t.save
    end

    puts "There are now #{Restaurant.count} rows in the restaurant table"
  end

  private

  def calculate_rating
    Review.where(restaurant_id: id).average(:rating)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :set_all_cuisine, only: [:show, :new, :edit]
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def set_all_cuisine
      @cuisines = Cuisine.all
    end

    # require params methods
    def restaurant_params
      params.require(:restaurant).permit(:name, :rating, :tenbis, :address, :kosher, :max_delivery_time, :cuisine_id)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name %>
  </div>

  <div class="field">
    <%= form.label :cuisine_id %>
    <%= form.collection_select :cuisine_id,  @cuisines, :id ,:name %>
  </div>

  <!--<div class="field">-->
    <!--<%= form.label :rating %>-->
    <!--<%= form.select(:rating, [['0',0],['1',1] ,['2',2], ['3',3]])%>-->
  <!--</div>-->

  <div class="field">
    <%= form.label :ten_bis %>
    <%= form.check_box :ten_bis, id: :restaurant_10bis %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :restaurant_address %>
  </div>

  <div class="field">
    <%= form.label :kosher %>
    <%= form.check_box :kosher, id: :restaurant_kosher %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cuisine</th>
      <th>Rating</th>
      <th>10bis</th>
      <th>Address</th>
      <th>Kosher</th>
      <th>Maxdevtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.cuisine_id %></td>
        <td><%= restaurant.rating %></td>
        <td><%= restaurant.ten_bis %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.kosher %></td>
        <td><%= restaurant.max_delivery_time %></td>


        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= link_to 'New Restaurant', new_restaurant_path %>
<%= link_to 'Add Restaurants from csv', store_index_path, @restaurants.first.parse_csv('Restaurants-ALL.csv') %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @restaurant.cuisine_id %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @restaurant.rating %>
</p>

<p>
  <strong>10bis:</strong>
  <%= @restaurant.ten_bis %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Kosher:</strong>
  <%= @restaurant.kosher %>
</p>

<p>
  <strong>max_delivery_time:</strong>
  <%= @restaurant.max_delivery_time %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>