config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :cuisines
  root 'store#index', as: 'store_index'

  get 'store/index'

  resources :reviews
  resources :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @restaurant_id = params[:restaurant_id]
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    # save user info
    user_validate

    # save max_delivery_time to restaurant
    update_max_delivery_time(@review.restaurant_id)

    respond_to do |format|
      if @review.save
        format.html { redirect_to store_index_path, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { redirect_to  new_review_path(restaurant_id: restaurant_id),notice: "Missing parameters #{@review.errors.full_messages}" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_review
      @review = Review.find(params[:id])
    end

    # require params methods
    def review_params
      params.require(:review).permit(:rating, :comment, :restaurant_id)
    end

    def user_params
      params.require(:review).permit(:name, :email)
    end

    def update_max_delivery_time(restaurant_id)
      review_max_delivery_time = Integer(params[:review][:max_delivery_time])
      cur_restaurant = Restaurant.find(restaurant_id)

      cur_restaurant.update!(max_delivery_time: [review_max_delivery_time, cur_restaurant.max_delivery_time].max)
    end

    def user_validate
      @review.user = User.where(email: user_params[:email]).first_or_create!(user_params)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :rating %>
    <%= form.select(:rating, [['0',0],['1',1] ,['2',2], ['3',3]])%>
  </div>

  <div class="field">
    <%= form.label :rest %>
    <%= form.hidden_field :restaurant_id, value: @restaurant_id %>

  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :review_comment %>

  </div>


  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :name, id: :user_name %>

  </div>

  <div class="field">
    <%= form.label :user_email %>
    <%= form.text_field :email, id: :user_email %>

  </div>

  <div class="field">
    <%= form.label :max_delivery_time %>
    <%= form.select(:max_delivery_time, [[0,0],[15,15] ,[30,30], [60,60]])%>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.user.name %></td>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= review.restaurant_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Rest:</strong>
  <%= @review.restaurant_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>